/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_algorithm4_library_algorithm4library_Algorithm4SensorLib */
#include "Algorithm4Bodystm.h"

#ifndef _Included_com_algorithm4_library_algorithm4library_Algorithm4SensorLib
#define _Included_com_algorithm4_library_algorithm4library_Algorithm4SensorLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    InitSingleInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_InitSingleInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    SetTargetSampling
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_SetTargetSampling
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    getValue
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_getValue
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    getSampledData
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_getSampledData
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    addRecvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_addRecvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    GeneralCmd4Dev
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_GeneralCmd4Dev
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    GetCmdResult
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_GetCmdResult
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    GetSensorMsg
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_GetSensorMsg
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4SensorLib
 * Method:    GetCentorMac
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4SensorLib_GetCentorMac
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
