/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_algorithm4_library_algorithm4library_Algorithm4Library */

#ifndef _Included_com_algorithm4_library_algorithm4library_Algorithm4Library
#define _Included_com_algorithm4_library_algorithm4library_Algorithm4Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    InitSingleInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_InitSingleInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    addData
 * Signature: ([[BII)I
 */
JNIEXPORT jint JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_addData
  (JNIEnv *, jclass, jobjectArray, jint, jint);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    SetTargetSampling
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_SetTargetSampling
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    getValue
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_getValue
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    getSampledData
 * Signature: ([[D[D)V
 */
JNIEXPORT void JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_getSampledData
  (JNIEnv *, jclass, jobjectArray, jdoubleArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    addRecvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_addRecvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    GeneralCmd4Dev
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_GeneralCmd4Dev
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_algorithm4_library_algorithm4library_Algorithm4Library
 * Method:    GetCmdResult
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_algorithm4_library_algorithm4library_Algorithm4Library_GetCmdResult
  (JNIEnv *, jclass, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
